ALTER TABLE products
  ADD COLUMN IF NOT EXISTS name_urdu TEXT,
  ADD COLUMN IF NOT EXISTS expected_stock INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS admin_media_required BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS product_uid TEXT;
